# Generated by Django 4.1.1 on 2022-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ratting_percentage',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
