# Generated by Django 4.1.1 on 2022-10-07 09:57

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_ratting_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertUserLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to=courses.models.upload_image_path)),
                ('ig_link', models.URLField()),
            ],
        ),
    ]
