# Generated by Django 4.1.1 on 2022-10-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
