# Generated by Django 4.1.1 on 2022-10-08 07:38

import courses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_course_is_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRattingAndComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rattings', models.PositiveBigIntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', courses.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseratings',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseratings',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
        migrations.DeleteModel(
            name='CourseRatings',
        ),
    ]
