# Generated by Django 4.1.1 on 2022-10-08 07:44

import courses.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courserattingandcomment_remove_courseratings_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserattingandcomment',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='courserattingandcomment',
            name='updated_at',
            field=courses.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
