# Generated by Django 4.1.1 on 2022-10-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courserattingandcomment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserattingandcomment',
            old_name='rattings',
            new_name='ratings',
        ),
    ]
